#!/usr/bin/perl
use Cwd;
print "Hello world!\n";
#1. Get command line arguments.
use Cwd;
my @args = @ARGV;
#3. import data files.
my $pdblocation = "/home/home3/swati/OSPREY_v2.1beta_Dec2012/Experiments";
print"Creating directory $args[0]\n";
system("mkdir $args[0]");
system("mkdir $args[0]/import");
system("cp -r $pdblocation/$args[0]/* $args[0]/import/.");
system("mv $args[0]/import/*min*.pdb $args[0]/$args[0].pdbresult");
system("cp $args[0]/import/*.pdb $args[0]/$args[0].pdb");
system("cp $args[0]/import/DEE*.cfg $args[0]/DEE.cfg");
system("cp $args[0]/import/System*.cfg $args[0]/System.cfg");
chdir("$args[0]/");
#2. Convert config files.
# add bd info to BWM.cfg
my $fileName = "";
open (my $DEEConfigFile, "<DEE.cfg")
	or die "Unable to open DEE.cfg\n";
open (my $output, ">$args[0]BWM.cfg") 
	or die "Unable to create Cleaned pdb file for writing.\n";
while(<$DEEConfigFile>)
{
	chomp;
	my $line = $_;
	$line =~ s/\r//g;
	print $output "$line\n";
}
print $output "prunedRotFile $args[0]_pruneInfo.obj\n";
print $output "branchDfile $args[0]bd\n";
# change pdb and run names
open (my $systemConfigFile, "<System.cfg")
	or die "Unable to open System.cfg.\n";
open (my $output, ">$args[0]System.cfg") 
	or die "Unable to create Cleaned pdb file for writing.\n";
while(<$systemConfigFile>)
{
	my $line = $_;
	if($line =~ m/pdbName/)
	{
		$line = "pdbName data/$args[0].pdb\n";
	}
	print $output $line;
}
# move the config and pdb files
system("cp $args[0]BWM.cfg ../config/.");
system("cp $args[0]System.cfg ../config/.");
system("cp $args[0].pdb ../data/.");
#3. call runBWM.
chdir("..");
$ENV{CLASSPATH} = "$ENV{CLASSPATH}:bin";
$currentDirectory = getcwd();
print "We're in $currentDirectory\n";
system("java -Xmx60000M kstar/KStar -t 3 -c config/KStar.cfg doBWM config/$args[0]System.cfg config/$args[0]BWM.cfg");
print "End\n";
