#!/usr/bin/perl
use Cwd;
print "Hello world!\n";
$ENV{CLASSPATH} = "$ENV{CLASSPATH}:bin:src/BranchDecomposition/jmatharray.jar";
$currentDirectory = getcwd();
print "We're in $currentDirectory\n";
system("java -Xmx4000M kstar/KStar -c config/KStar.cfg doBWM System.cfg DEE.cfg");
