#!/usr/bin/perl
use Cwd;
print "Hello world!\n";
$ENV{CLASSPATH} = "$ENV{CLASSPATH}:bin";
$currentDirectory = getcwd();
print "We're in $currentDirectory\n";
system("java -Xmx60000M kstar/KStar -c config/KStar.cfg doDEE config/System.cfg config/DEE.cfg");
